name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]  # Node.js versions to test with

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print current directory for debugging purposes
      - name: Check current directory
        run: pwd

      # Step 3: List files to verify package.json is in the correct location
      - name: List files
        run: ls -la

      # Step 4: Set up Node.js environment for the specified versions
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 5: Install dependencies (npm install)
      - name: Install dependencies
        run: npm install

      # Step 6: Install Playwright globally (to ensure correct permissions)
      - name: Install Playwright globally
        run: npm install -g playwright

      # Step 7: Check if Playwright was installed successfully
      - name: Check Playwright installation
        run: npx playwright --version

      # Step 8: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Step 9: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
